default:
  DATABASE_URL: ""
  DIRS_EXCLUDED:
  - .static
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
    - src/applications/main/templates/
  HMODE_DEBUG: false
  MODE_PROFILING: false
  HOST: ""
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000


ci:
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  MODE_DEBUG: false
  VENV_SYNTHETIC: 1
